name: Sky Q Hub Release

on:
  release:
    types: [published]

jobs:
  releasenotes:
    name: Prepare release notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Enable version 3.7 of Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel
          python3 -m pip install -r /home/runner/work/skyq_hub/skyq_hub/requirements_release.txt

      - name: Update release notes
        run: python3 /home/runner/work/skyq_hub/skyq_hub/manage/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}
